apiVersion: v1
kind: Service
metadata:
  name: mongos
  labels:
    name: mongos
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongos
---
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongos
  namespace: default
spec:
  serviceName: mongos
  replicas: 2
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
      - name: mongos
        image: docker.io/mongo:4.2
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ["mongos"]
        args: ["--configdb", "cfgrs/mongocfg-0.mongocfg:27019,mongocfg-1.mongocfg:27019,mongocfg-2.mongocfg:27019", "--bind_ip_all"]
        resources:
          limits:
            cpu: 1
            memory: 1500Mi
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - name: port
          containerPort: 27017
        volumeMounts:
        - name: mongos-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongos-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: # using the default "standard"
      resources:
        requests:
          storage: 2Gi